[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_22']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm install']

[phases.build]
cmds = ['npm run build', 'php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache']

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --class=AnimalesSeeder --force && php artisan optimize && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT'
